### ISSUE TITLE
EFEKTA Zigbee Plant Watering Sensor compatibility with Home Assistant ZHA?

### ISSUE THREAD

**Issue by Gamester17** [smartboxchannel/Plant-Watering-Sensor-Zigbee#3]
Is this EFEKTA Zigbee Plant Watering Sensor compatibility with Home Assistant ZHA?

https://www.home-assistant.io/integrations/zha

Would like to know if its sensors and attributes are properly detected out-of-the-box by ZHA?

Blakadder open compatibility database list only confirms it working with Zigbee2MQTT:

https://zigbee.blakadder.com/EFEKTALAB_EFEKTA_PWS.html

**Comment by smartboxchannel** [comment]
plz try hex https://github.com/smartboxchannel/Plant-Watering-Sensor-Zigbee/tree/main/PROJECT%20SOURCE

**Comment by Hedda** [comment]
Assume that it will still need a quirk as discussed in https://github.com/zigpy/zha-device-handlers/issues/1171 ?

**Comment by smartboxchannel** [comment]
ZHA now supports soil moisture and earlier I made a version under ZHA, where soil moisture was transmitted through humidity

**Comment by aog2000a** [comment]
@Hedda I needed a quirk because in my device FW the in_ and out_channels were exchanged with respect to what ZHA was expecting, but now it is working perfectly :-) I would be able to avoid the ZHA quirk if i would reflash the device with the corrected FW, but I need a debugger etc so...

Thanks @smartboxchannel !
